version: '3.3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=api/__init__.py
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=${REACT_APP_BACKEND_SERVICE_URL}
    depends_on:
      - backend  

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend 